version: "3.9"

services:
  db:
    image: postgres:15
    container_name: projectcollab_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectcollab
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: projectcollab_backend
    command: npm run dev
    volumes:
      - ../backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/projectcollab
    depends_on:
      - db

  frontend:
    build: ../frontend
    container_name: projectcollab_frontend
    command: npm run dev
    volumes:
      - ../frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend

volumes:
  db_data:
